name: event-nn
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.3
  - nlopt=2.7
  - opencv=4.5
  - pip=21.0
  - python=3.8
  - scipy=1.7
  - pip:
    - flow_vis==0.1
    - tensorflow==2.8.*
    - tensorflow-addons==0.13.*
